[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "nitro-boost"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "blinker>=1.9.0",
    "datastar-py>=0.6.5",
    "pydantic>=2.11.9",
]
[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "nitro"  # Match your crate name
python-packages = ["nitro"]  # Your Python package name
